In [70]:
import pandas as pd
print(pd.__version__)
import numpy as np
print(np.__version__)

3.0.6
2.5.4

In [71]:
df = pd.read_csv("../data/raw/journal_entries_4203.csv", sep=";")
df.head() # shows the first five lines of the document

,posting_id,document_date,posting_date,entered_date,gl_account,gl_account_name,amount,cd_flag,user,tax_rate,ref_id,text,promptly,weekend,nwh,label,marking,top_n,high_cash
0,a_1,2023-05-31,2023-05-31,2023-06-01 11:52:40,3400,"Cost of merchandise, 19% input tax",112.42,D,David,0.19,0,Rake,1,0,0,0,0,0,0
1,a_1,2023-05-31,2023-05-31,2023-06-01 11:52:40,1576,"Deductible input tax, 19%",21.36,D,David,0.19,0,Rake,1,0,0,0,0,0,0
2,a_1,2023-05-31,2023-05-31,2023-06-01 11:52:40,1600,Trade payables,133.78,C,David,0.19,0,Rake,1,0,0,0,0,0,0
3,a_2,2023-01-26,2023-01-26,2023-02-02 16:21:22,3400,"Cost of merchandise, 19% input tax",934.00,D,Bob,0.19,0,Lawn Mower,1,0,0,0,0,0,0
4,a_2,2023-01-26,2023-01-26,2023-02-02 16:21:22,1576,"Deductible input tax, 19%",177.46,D,Bob,0.19,0,Lawn Mower,1,0,0,0,0,0,0

In [72]:
df.info() #Ver informação sobre o dataset

<class 'pandas.DataFrame'>
RangeIndex: 256232 entries, 0 to 256231
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   posting_id       256232 non-null  str
 1   document_date    256232 non-null  str
 2   posting_date     256232 non-null  str
 3   entered_date     256232 non-null  str
 4   gl_account       256232 non-null  int64
 5   gl_account_name  256232 non-null  str
 6   amount           256232 non-null  float64
 7   cd_flag          256232 non-null  str
 8   user             256232 non-null  str
 9   tax_rate         256232 non-null  float64
 10  ref_id           256232 non-null  str
 11  text             256232 non-null  str
 12  promptly         256232 non-null  int64
 13  weekend          256232 non-null  int64
 14  nwh              256232 non-null  int64
 15  label            256232 non-null  int64
 16  marking          256232 non-null  int64
 17  top_n            256232 non-null  int64
 18  high_cash        256232 non-null  int64
dtypes: float64(2), int64(8), str(9)
memory usage: 37.1 MB

In [73]:
df["posting_date"].head()

0    2023-05-31
1    2023-05-31
2    2023-05-31
3    2023-01-26
4    2023-01-26
Name: posting_date, dtype: str

In [74]:
df["document_date"] = pd.to_datetime(df["document_date"])
df["posting_date"] = pd.to_datetime(df["posting_date"])
df["entered_date"] = pd.to_datetime(df["entered_date"])

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 256232 entries, 0 to 256231
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   posting_id       256232 non-null  str
 1   document_date    256232 non-null  datetime64[us]
 2   posting_date     256232 non-null  datetime64[us]
 3   entered_date     256232 non-null  datetime64[us]
 4   gl_account       256232 non-null  int64
 5   gl_account_name  256232 non-null  str
 6   amount           256232 non-null  float64
 7   cd_flag          256232 non-null  str
 8   user             256232 non-null  str
 9   tax_rate         256232 non-null  float64
 10  ref_id           256232 non-null  str
 11  text             256232 non-null  str
 12  promptly         256232 non-null  int64
 13  weekend          256232 non-null  int64
 14  nwh              256232 non-null  int64
 15  label            256232 non-null  int64
 16  marking          256232 non-null  int64
 17  top_n            256232 non-null  int64
 18  high_cash        256232 non-null  int64
dtypes: datetime64[us](3), float64(2), int64(8), str(6)
memory usage: 37.1 MB

In [76]:
df["posting_date"].min()

Timestamp('2023-01-02 00:00:00')

In [77]:
df["posting_date"].max()

Timestamp('2024-12-30 00:00:00')

In [78]:
df.dtypes # Mostra o tipo de dados de cada coluna do csv

posting_id                    str
document_date      datetime64[us]
posting_date       datetime64[us]
entered_date       datetime64[us]
gl_account                  int64
gl_account_name               str
amount                    float64
cd_flag                       str
user                          str
tax_rate                  float64
ref_id                        str
text                          str
promptly                    int64
weekend                     int64
nwh                         int64
label                       int64
marking                     int64
top_n                       int64
high_cash                   int64
dtype: object

In [79]:
print("Linhas:", len(df)) # Número de linhas da tabela
print("Lançamentos:", df["posting_id"].nunique()) # Vai à coluna posting_id e conta quantos valores unicos existem, unique mostrava os valores diferentes
print("Contas:", df["gl_account"].nunique())
print("Users:", df["user"].nunique())

Linhas: 256232
Lançamentos: 102429
Contas: 25
Users: 6

In [80]:
df["cd_flag"].value_counts() #Vai contar quantas vezes aparece cada valor

cd_flag
D    135743
C    120489
Name: count, dtype: int64

In [81]:
df["signed_amount"] = np.where(df["cd_flag"] == "D", df["amount"], -df["amount"])
df[["posting_id", "cd_flag", "amount", "signed_amount"]].head()

  posting_id cd_flag  amount  signed_amount
0        a_1       D  112.42         112.42
1        a_1       D   21.36          21.36
2        a_1       C  133.78        -133.78
3        a_2       D  934.00         934.00
4        a_2       D  177.46         177.46

In [82]:
filtro = df["posting_id"] == "a_1"
print(df[filtro][["posting_id", "cd_flag", "amount", "signed_amount"]])
print("Sum:", df[filtro]["signed_amount"].sum())

  posting_id cd_flag  amount  signed_amount
0        a_1       D  112.42         112.42
1        a_1       D   21.36          21.36
2        a_1       C  133.78        -133.78
Sum: 0.0

In [83]:
totais = df.groupby("posting_id")["signed_amount"].sum()
totais.head()

posting_id
a_1        0.0
a_10       0.0
a_100      0.0
a_1000     0.0
a_10000    0.0
Name: signed_amount, dtype: float64

In [84]:
filtro = df["posting_id"] == "p_2"
print("Linhas:", filtro.sum())
print(df[filtro][["posting_id", "gl_account_name", "cd_flag", "amount", "signed_amount"]])
print("Sum:", df[filtro]["signed_amount"].sum())

Linhas: 4
       posting_id            gl_account_name cd_flag   amount  signed_amount
256224        p_2          Other liabilities       D  1490.90        1490.90
256225        p_2      Prior-period expenses       D    63.36          63.36
256226        p_2  Deductible input tax, 19%       D   295.31         295.31
256227        p_2             Trade payables       C  1849.57       -1849.57
Sum: 0.0

In [87]:
filtro_nao_zero = totais != 0

print("Lançamentos com total diferente de zero:", filtro_nao_zero.sum())

totais[filtro_nao_zero].head()

filtro_desequilibrados = totais.round(2) != 0

print("Lançamentos desequilibrados:", filtro_desequilibrados.sum())

Lançamentos com total diferente de zero: 19452
Lançamentos desequilibrados: 0